/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_EtchWin32_WRAP_H_
#define SWIG_EtchWin32_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Printable : public Printable, public Swig::Director {

public:
    SwigDirector_Printable(VALUE self);
    virtual ~SwigDirector_Printable();
    virtual void print(PrintContext *ctx);
};


#endif
